=== Lurkki14/omorfi/src/disamparsulation/disamparsulations.dtd
<!--
   Copyright 2018 Flammie A Pirinen, Omorfi contributors

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; version 3 and not later,

   This program is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not <http://www.gnu.org/licenses/>.
-->
<!ELEMENT disamparsulations (evidence*)>
<!ATTLIST disamparsulations
    version CDATA #REQUIRED
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT evidence (target, likelihood, depname?, context?)>
<!ATTLIST evidence
    name CDATA #REQUIRED>
<!ELEMENT target (upos?, ufeats?)>
<!ELEMENT upos (#PCDATA)>
<!ELEMENT ufeats (ufeat*)>
<!ELEMENT ufeat (#PCDATA)>
<!ATTLIST ufeat
    name CDATA #REQUIRED>
<!ELEMENT likelihood (#PCDATA)>
<!ELEMENT depname (#PCDATA)>
<!ELEMENT context (location, upos?, ufeats?, barrier?)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT barrier (upos?, ufeats?)>

=== Lurkki14/omorfi/src/disamparsulation/omorfi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE disamparsulations SYSTEM "disamparsulations.dtd">
<!--
  Copyright (c) 2018 Omorfi contributors

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, version 3 of the License

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<disamparsulations version="0.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="disamparsulations.xsd"
    xmlns:html="http://www.w3.org/1999/xhtml">
  <matchers>
    <matcher name="nominal">
      <match>
        <upos>NOUN</upos>
        <upos>ADJ</upos>
        <upos>PRON</upos>
        <upos>PROPN</upos>
      </match>
    </matcher>
  </matchers>
  <evidences>
    <!-- {{{ Single word stuffs -->
    <evidence name="instructives unlikely">
      <documentation>
        <example>hän oli ryhmänsä nopein</example>
      </documentation>
      <target>
        <match>
          <ufeats>
            <ufeat name="Case">Ins</ufeat>
          </ufeats>
        </match>
      </target>
      <likelihood>unlikely</likelihood>
    </evidence>
    <!-- }}}
         {{{ deps -->
    <evidence name="puncts to nearest main verb">
      <target>
        <match>
          <upos>PUNCT</upos>
        </match>
      </target>
      <likelihood>usually</likelihood>
      <depname>punct</depname>
      <context>
        <location>any</location>
        <match>
          <upos>VERB</upos>
        </match>
        <barrier>
          <match>
            <upos>PUNCT</upos>
          </match>
        </barrier>
      </context>
    </evidence>
    <evidence name="verbs can be roots">
      <target>
        <match>
          <upos>VERB</upos>
        </match>
      </target>
      <likelihood>probably</likelihood>
      <depname>root</depname>
      <context>
        <location>ROOT</location>
      </context>
    </evidence>
    <evidence name="cconj coordinates its +1">
      <target>
        <match>
          <upos>CCONJ</upos>
        </match>
      </target>
      <likelihood>probably</likelihood>
      <depname>conj</depname>
      <context>
        <location>+1</location>
      </context>
    </evidence>
    <evidence name="elative adj agrees its +1">
      <target>
        <match>
          <upos>ADJ</upos>
          <ufeats>
            <ufeat name="Case">Ela</ufeat>
          </ufeats>
        </match>
      </target>
      <likelihood>usually</likelihood>
      <depname>amod</depname>
      <context>
        <location>+1</location>
        <match>
          <ufeats>
            <ufeat name="Case">Ela</ufeat>
          </ufeats>
        </match>
      </context>
    </evidence>
    <evidence name="1sg pronoung agrees with 1sg verb">
      <target>
        <match>
          <upos>PRON</upos>
          <ufeats>
            <ufeat name="PronType">Prs</ufeat>
            <ufeat name="Number">Sing</ufeat>
            <ufeat name="Person">1</ufeat>
          </ufeats>
        </match>
      </target>
      <likelihood>usually</likelihood>
      <depname>nsubj</depname>
      <context>
        <location>any</location>
        <match>
          <upos>VERB</upos>
          <ufeats>
            <ufeat name="Number">Sing</ufeat>
            <ufeat name="Person">1</ufeat>
          </ufeats>
        </match>
        <barrier>
          <match>
            <upos>VERB</upos>
          </match>
        </barrier>
      </context>
    </evidence>
    <evidence name="Numeral modifier for nom takes par">
      <target>
        <match>
          <upos>NUM</upos>
          <ufeats>
            <ufeat name="NumType">Card</ufeat>
            <ufeat name="Number">Sing</ufeat>
            <ufeat name="Case">Nom</ufeat>
          </ufeats>
        </match>
      </target>
      <likelihood>usually</likelihood>
      <depname>nummod</depname>
      <context>
        <location>+1</location>
        <match>
          <upos>NOUN</upos>
        <ufeats>
          <ufeat name="Number">Sing</ufeat>
          <ufeat name="Case">Par</ufeat>
        </ufeats>
      </match>
      </context>
    </evidence>
    <evidence name="Partitives can be objects">
      <target>
        <match>
          <upos>NOUN</upos>
          <ufeats>
            <ufeat name="Case">Par</ufeat>
          </ufeats>
        </match>
      </target>
      <likelihood>possibly</likelihood>
      <depname>obj</depname>
      <context>
        <location>any</location>
        <match>
          <upos>VERB</upos>
        </match>
        <barrier>
          <match>
            <upos>PUNCT</upos>
          </match>
        </barrier>
      </context>
    </evidence>
    <evidence name="Adverbs are ad verbs">
      <target>
        <match>
          <upos>ADV</upos>
        </match>
      </target>
      <likelihood>possibly</likelihood>
      <depname>advmod</depname>
      <context>
        <location>any</location>
        <match>
          <upos>VERB</upos>
        </match>
        <barrier>
          <match>
            <upos>PUNCT</upos>
          </match>
        </barrier>
      </context>
    </evidence>
    <evidence name="Genitive prn to possessive">
      <target>
        <match>
          <upos>PRON</upos>
          <ufeats>
            <ufeat name="PronType">Prs</ufeat>
            <ufeat name="Case">Gen</ufeat>
            <ufeat name="Number">Sing</ufeat>
            <ufeat name="Person">2</ufeat>
          </ufeats>
        </match>
      </target>
      <likelihood>usually</likelihood>
      <depname>nmod:poss</depname>
      <context>
        <location>right</location>
        <match>
          <ufeats>
            <ufeat name="Number[psor]">Sing</ufeat>
            <ufeat name="Person[psor]">2</ufeat>
          </ufeats>
        </match>
        <barrier>
          <match>
            <upos>PUNCT</upos>
          </match>
        </barrier>
      </context>
    </evidence>
  </evidences>
</disamparsulations>
